name: Pull changes from BlueOS
on:
  repository_dispatch:
    types: [blueos-pull]
  # 定时触发
  schedule:
    - cron: "29 2 * * 1,4"
  # 允许网页界面手动触发
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
# 并发控制
concurrency:
  group: blueos-pull
  cancel-in-progress: false
jobs:
  pull:
    if: ${{ vars.JOSH_SYNC_ENABLED == 'true' }}
    uses: vivoblueos-lab/josh-sync/.github/workflows/blueos-pull.yml@f5b1a27b4b5977dc9b71145565000f2e99a9e81e
    with:
      # 这里的 JOSH_SYNC_APP_CLIENT_ID 和 JOSH_SYNC_APP_PRIVATE_KEY 是从组织变量和秘密中获取的
      github-app-client-id: ${{ vars.JOSH_SYNC_APP_CLIENT_ID }}
      # xxx[bot] 这里的 xxx, 就是 GitHub App 的名称
      pr-author: "blueos-josh-sync[bot]"
      josh-sync-repository: vivoblueos-lab/josh-sync
      # 和上文的 workflow 版本保持一致
      josh-sync-revision: f5b1a27b4b5977dc9b71145565000f2e99a9e81e
      branch-name: blueos-pull
      # 这里填的是当前子仓库的默认分支, libc的比较特殊
      pr-base-branch: main
    secrets:
      github-app-secret: ${{ secrets.JOSH_SYNC_APP_PRIVATE_KEY }}
