name: Push librs changes to BlueOS
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: blueos-push-${{ github.repository }}
  cancel-in-progress: false
jobs:
  push:
    if: ${{ vars.JOSH_SYNC_ENABLED == 'true' }}
    uses: vivoblueos-lab/josh-sync/.github/workflows/blueos-push.yml@796048c8dc8ed770883aadacd3f925fe69038134
    with:
      github-app-client-id: ${{ vars.APP_CLIENT_ID }}
      josh-sync-repository: vivoblueos-lab/josh-sync
      josh-sync-revision: 796048c8dc8ed770883aadacd3f925fe69038134
    secrets:
      github-app-secret: ${{ secrets.APP_PRIVATE_KEY }}
